import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/Card";
import Filter from "../components/Filter";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark:bg-darkSecondary ">
        <Navbar />
        <section className="flex  flex-col md:flex-row mx-auto p-4  max-w-screen-xl justify-between ">
          <Filter />

          <div className="space-y-4">
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
          </div>
        </section>
        <Footer />
      </main>
    </>
  );
};

export default Home;
