import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/Card";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section className="flex mx-auto p-4 m-4">
          <div className="bg-black text-white p-4">
            <h2>Filter Candidates</h2>
          </div>
          <Card />
        </section>
      </main>
    </div>
  );
};

export default Home;
